# Generated by Django 5.1.1 on 2024-09-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaucetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("wallet_address", models.CharField(max_length=100)),
                ("last_request_time", models.DateTimeField(auto_now_add=True)),
                ("created_at_time", models.DateTimeField(auto_now_add=True)),
                ("updated_at_time", models.DateTimeField(auto_now=True)),
                ("success", models.BooleanField()),
                ("failure_reason", models.CharField(max_length=200, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="faucet_api__ip_addr_429684_idx"
                    ),
                    models.Index(
                        fields=["wallet_address"], name="faucet_api__wallet__bbec49_idx"
                    ),
                ],
            },
        ),
    ]
